name: BrainDown
options:
  bundleIdPrefix: com.kenefe
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  minimumXcodeGenVersion: "2.35.0"

packages:
  Highlightr:
    url: https://github.com/raspu/Highlightr
    from: "2.2.1"
  Yams:
    url: https://github.com/jpsim/Yams
    from: "5.1.3"

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.kenefe.BrainDown
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: BrainDown
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.productivity"
    CODE_SIGN_ENTITLEMENTS: Resources/BrainDown.entitlements
    CODE_SIGN_STYLE: Manual
    CODE_SIGN_IDENTITY: "-"
    DEVELOPMENT_TEAM: ""

targets:
  BrainDown:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "BDVerify.swift"
      - path: Sources/BlockViews
      - path: Resources/Assets.xcassets
        buildPhase: resources
    dependencies:
      - package: Highlightr
      - package: Yams
    settings:
      base:
        PRODUCT_NAME: BrainDown
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

  bd-verify:
    type: tool
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "BrainDownApp.swift"
          - "ContentView.swift"
          - "FileTreeView.swift"
          - "FileTypeSettings.swift"
          - "AppSettings.swift"
          - "MarkdownEditorView.swift"
          - "SyntaxHighlighter.swift"
          - "FileManager+Extensions.swift"
      - path: Sources/BlockViews
    dependencies:
      - package: Highlightr
    settings:
      base:
        PRODUCT_NAME: bd-verify
